version: '3.8'

services:
  app:
    build: .
    container_name: go-notifier
    ports:
      - "8000:8000"
      - "8081:8081"
    environment:
      - SMTP_HOST=${SMTP_HOST} 
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SENDER=${SMTP_SENDER}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}


      - KANNEL_URL=${KANNEL_URL}
      - KANNEL_USERNAME=${KANNEL_USERNAME}
      - KANNEL_PASSWORD=${KANNEL_PASSWORD}
      - KANNEL_SENDER=${KANNEL_SENDER}


      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mailhog
      - kannel
      - postgres

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # Web UI

  kannel:
    build: ./kannel
    container_name: kannel
    ports:
      - "13000:13000"
      - "13013:13013"
    volumes:
      - ./kannel/kannel.conf:/etc/kannel/kannel.conf
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: notificationdb         
    ports:
      - "5432:5432"                     
    shm_size: 128mb
    volumes:
      - pgdata:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"  # http://localhost:8080

volumes:
  pgdata: